
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.89
loader_version_range=[1,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=furnacering
mod_name=Furnace Ring
mod_license=OSL-3.0
mod_version=neoforge-1.21.1-1.0.0
mod_group_id=gottsch
mod_authors=gottsch
mod_description=New take on the classic portable furnaces mod - Ring Furnaces - Smelt at all times!

curios_version=9.5.1+1.21.1